# Generated by Django 5.1.5 on 2025-01-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_create_service_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'title']},
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=0, help_text='Order in which this service appears (lower numbers first)'),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
