# Generated by Django 5.1.5 on 2025-01-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sociallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text="\n        Markdown formatted text. Use:\n        * For bullet points, start lines with '* '\n        * For paragraphs, leave a blank line between them\n        * For emphasis, use *italics* or **bold**\n        * For line breaks, use a blank line between paragraphs\n    "),
        ),
    ]
