# Generated by Django 5.1.5 on 2025-02-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('hero_image_filename', models.CharField(help_text='Filename of the hero image in static/images/', max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='Only active posts will be shown on the site')),
                ('content', models.TextField(help_text='\n        Markdown formatted text. Supports:\n        * Headers (# ## ###)\n        * Lists (* or -)\n        * Links [text](url)\n        * Images ![alt](/static/images/filename)\n        * Code blocks (```)\n        * Emphasis (*italic* or **bold**)\n        ')),
                ('meta_description', models.CharField(help_text='SEO meta description, recommended length 150-160 characters', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
