# Generated by Django 5.1.5 on 2025-02-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_html',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='hero_image_alt',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='hero_image_filename',
            field=models.CharField(blank=True, help_text='Filename of the hero image in static/images/', max_length=100),
        ),
    ]
