# Generated by Django 5.1.5 on 2025-04-21 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_blogpost_content_html_blogpost_hero_image_alt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='detail_url',
            field=models.URLField(blank=True, help_text='Optional URL to a detailed page about this service', null=True),
        ),
    ]
