# Generated by Django 5.1.5 on 2025-04-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_service_detail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='detail_url',
            field=models.CharField(blank=True, help_text="Final part of the URL (e.g. 'roof_replacement.html')", max_length=100, null=True),
        ),
    ]
