# Generated by Django 5.1.5 on 2025-04-21 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_service_detail_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='detail_url',
        ),
    ]
