# Generated by Django 5.2 on 2025-11-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_service_detail_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text="Customer's full name", max_length=200)),
                ('project_tag', models.CharField(help_text="Unique project identifier for Drive filtering (e.g., '2025-10 Sherrene Kibbe')", max_length=100, unique=True)),
                ('emails', models.JSONField(default=list, help_text="List of email addresses with access to this portal (e.g., ['customer@email.com', 'david@tetralto.com'])")),
                ('project_date', models.DateField(help_text='Date of the roofing project')),
                ('shingle_brand', models.CharField(help_text='Brand of shingles used', max_length=100)),
                ('shingle_color', models.CharField(help_text='Color of shingles', max_length=100)),
                ('has_left_review', models.BooleanField(default=False, help_text='Has customer left a Google review? (manually update in admin)')),
                ('drive_folder_id', models.CharField(blank=True, help_text='Optional: Google Drive folder ID to scope queries (leave blank to search all accessible files)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer Portal',
                'verbose_name_plural': 'Customer Portals',
                'ordering': ['-project_date', '-created_at'],
            },
        ),
    ]
