# Generated by Django 5.2 on 2025-11-13 01:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_portal'),
    ]

    operations = [
        # Drop the JSONB emails column
        migrations.RemoveField(
            model_name='portal',
            name='emails',
        ),
        # Recreate as ArrayField
        migrations.AddField(
            model_name='portal',
            name='emails',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254), 
                default=list, 
                help_text='List of email addresses with access to this portal', 
                size=None
            ),
        ),
    ]
